package PetclinicModules.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '269e1e6e-1ad6-4fba-b019-c13417ec561d' (id = 'PetclinicModules')
accordingly and delete the patch script.
*/
changeProject("269e1e6e-1ad6-4fba-b019-c13417ec561d") {
    features {
        add {
            feature {
                type = "CloudImage"
                id = "PROJECT_EXT_6"
                param("cpuReservationLimit", "90")
                param("cluster", "default")
                param("agent_pool_id", "-2")
                param("subnets", """
                    subnet-c24e129f
                    subnet-930ede9c
                """.trimIndent())
                param("taskDefinition", "teamcity-agent")
                param("maxInstances", "3")
                param("source-id", "1")
                param("launchType", "FARGATE")
            }
        }
        add {
            feature {
                type = "CloudImage"
                id = "PROJECT_EXT_7"
                param("cpuReservationLimit", "")
                param("cluster", "default")
                param("agentNamePrefix", "")
                param("assignPublicIp", "true")
                param("profileId", "awsecs-2")
                param("agent_pool_id", "-2")
                param("subnets", "subnet-930ede9c")
                param("taskDefinition", "teamcity-agent")
                param("maxInstances", "3")
                param("source-id", "1")
                param("launchType", "FARGATE")
                param("taskGroup", "")
            }
        }
        add {
            feature {
                type = "CloudImage"
                id = "PROJECT_EXT_8"
                param("cluster", "default")
                param("agent_pool_id", "-2")
                param("taskDefinition", "resource-name")
                param("source-id", "2")
                param("launchType", "EC2")
            }
        }
        add {
            feature {
                type = "CloudImage"
                id = "PROJECT_EXT_9"
                param("key-pair-name", "awsmicro")
                param("use-spot-instances", "false")
                param("security-group-ids", "sg-f881a590,")
                param("profileId", "amazon-1")
                param("ebs-optimized", "false")
                param("instance-type", "c3.large")
                param("source-id", "i-44a67639")
            }
        }
        add {
            feature {
                type = "CloudProfile"
                id = "amazon-1"
                param("profileServerUrl", "")
                param("secure:access-id", "credentialsJSON:8da96023-23b5-46da-becf-fec5b205dff8")
                param("total-work-time", "")
                param("description", "")
                param("cloud-code", "amazon")
                param("enabled", "true")
                param("max-running-instances", "3")
                param("agentPushPreset", "")
                param("profileId", "amazon-1")
                param("name", "ec2")
                param("next-hour", "")
                param("secure:secret-key", "credentialsJSON:b7d16088-a5c7-4bad-b0f8-6acec3833bff")
                param("region", "us-east-1")
                param("terminate-idle-time", "30")
                param("not-checked", "")
            }
        }
        add {
            feature {
                type = "CloudProfile"
                id = "awsecs-2"
                param("secure:aws.secret.access.key", "credentialsJSON:b7d16088-a5c7-4bad-b0f8-6acec3833bff")
                param("aws.external.id", "TeamCity-server-63ec393d-3f31-4b6e-bf2a-035ee247f58e")
                param("profileServerUrl", "")
                param("system.cloud.profile_id", "awsecs-2")
                param("total-work-time", "")
                param("aws.region.name", "us-east-1")
                param("description", "")
                param("cloud-code", "awsecs")
                param("enabled", "true")
                param("agentPushPreset", "")
                param("profileInstanceLimit", "")
                param("profileId", "awsecs-2")
                param("name", "esc")
                param("aws.access.key.id", "AKIAJYULYIVA4MVKZ2UA")
                param("aws.credentials.type", "aws.access.keys")
                param("next-hour", "")
                param("terminate-idle-time", "30")
                param("aws.iam.role.arn", "")
            }
        }
    }
}
