package PetclinicModules.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = 'efdeab34-bd5d-4b78-8a33-564cb60b5370' (id = 'PetclinicModules_PetclinicModulesWithBranches')
in the project with uuid = '269e1e6e-1ad6-4fba-b019-c13417ec561d' and delete the patch script.
*/
create("269e1e6e-1ad6-4fba-b019-c13417ec561d", GitVcsRoot({
    uuid = "efdeab34-bd5d-4b78-8a33-564cb60b5370"
    id = "PetclinicModules_PetclinicModulesWithBranches"
    name = "Petclinic Modules with branches"
    url = "https://github.com/antonarhipov/petclinic-modules"
    branchSpec = "+:refs/heads/*"
    authMethod = password {
        userName = "antonarhipov"
        password = "credentialsJSON:d9801888-f50b-4e9b-9132-1aafd4f3191b"
    }
}))

